# Generated by Django 4.2.6 on 2023-12-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media')),
                ('numero_registro', models.CharField(max_length=20, verbose_name='Registro Profissional')),
                ('nome_medico', models.CharField(max_length=200, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=200, verbose_name='Especialidade')),
                ('contato_profissional', models.CharField(max_length=15, null=True, unique=True, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200, verbose_name='Nome')),
                ('duracao_horas', models.PositiveIntegerField()),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.profissional')),
            ],
        ),
    ]
