# Generated by Django 5.0 on 2023-12-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=' media')),
                ('numero_registro', models.CharField(max_length=20, verbose_name='Registro Profissional')),
                ('nome_medico', models.CharField(max_length=200, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=200, verbose_name='Especialidade')),
                ('contato_profissional', models.CharField(max_length=15, null=True, unique=True, verbose_name='Contato')),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200, verbose_name='Nome')),
                ('duracao_horas', models.PositiveIntegerField(default=0)),
                ('duracao_minutos', models.PositiveIntegerField(default=0)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.profissional')),
            ],
        ),
    ]
