# Generated by Django 4.2.6 on 2023-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(upload_to=' media'),
        ),
    ]
