# Generated by Django 4.2.6 on 2023-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(upload_to=' media'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
