# Generated by Django 4.2.6 on 2023-12-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_profissional_options_alter_profissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao_horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
