# Generated by Django 5.0 on 2023-12-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
