# Generated by Django 4.2.6 on 2023-12-10 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=24, null=True, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('contato_paciente', models.CharField(max_length=15, null=True, unique=True, verbose_name='Contato')),
                ('cpf_paciente', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.')])),
            ],
        ),
    ]
