# Generated by Django 5.0 on 2023-12-27 02:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.')], verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
