# Generated by Django 5.0 on 2023-12-26 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.')], verbose_name='Cpf'),
        ),
    ]
