# Generated by Django 4.2.6 on 2023-12-10 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=24, null=True, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('contato_paciente', models.CharField(max_length=15, null=True, unique=True, verbose_name='Contato')),
                ('cpf_paciente', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.validate_integer, django.core.validators.MinLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=11, message='O CPF deve ter exatamente 11 dígitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media')),
                ('numero_registro', models.CharField(max_length=20, verbose_name='Registro Profissional')),
                ('nome_medico', models.CharField(max_length=200, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=200, verbose_name='Especialidade')),
                ('contato_profissional', models.CharField(max_length=15, null=True, unique=True, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200, verbose_name='Nome')),
                ('duracao_horas', models.PositiveIntegerField()),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('agenda_medica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.agendamedica')),
            ],
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
    ]
