# Generated by Django 4.2.6 on 2023-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=11),
        ),
    ]
