# Generated by Django 4.2.6 on 2023-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_cpf_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(default='medico', max_length=200, verbose_name='Especialidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(default='sddsdd', upload_to='caminho/do/upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome_medico',
            field=models.CharField(default='nome', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=11, verbose_name='cpf'),
        ),
    ]
