# Generated by Django 4.2.6 on 2023-11-29 17:37

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profissional_especialidade_profissional_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao_servico',
            field=models.DurationField(default=timedelta(minutes=30), verbose_name='Duração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(default='consulta', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
