# Generated by Django 4.2.6 on 2023-11-29 17:46

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_servico_duracao_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao_servico',
            field=models.DurationField(default=timedelta(minutes=30), verbose_name='Duração'),
            preserve_default=False,
        ),
    ]
