# Generated by Django 4.2.6 on 2023-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servico_duracao_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(related_name='Serviços', to='core.servico'),
        ),
    ]
