# Generated by Django 4.2.6 on 2023-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profissional_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(to='core.servico', verbose_name='Serviços'),
        ),
    ]
