# Generated by Django 4.2.7 on 2023-12-03 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profissional_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Servicos',
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_consulta',
            field=models.ForeignKey(default=1, limit_choices_to={'profissional__id': django.db.models.expressions.OuterRef('profissional')}, on_delete=django.db.models.deletion.CASCADE, to='core.servicos'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
    ]
