# Generated by Django 4.2.7 on 2023-12-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_servico_servicos_alter_servicos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='horario_final',
            field=models.TimeField(null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='horario_inicial',
            field=models.TimeField(null=True, verbose_name='Horário de Início'),
        ),
    ]
