# Generated by Django 4.2.7 on 2023-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profissional_horario_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=24, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
    ]
