# Generated by Django 4.2.6 on 2023-12-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.profissional')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('agenda_medica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agenda_medico.agendamedica')),
            ],
        ),
    ]
