# Generated by Django 4.2.6 on 2023-12-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0002_alter_profissional_options_alter_profissional_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de fim')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medico.profissional')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('agenda_medica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_selecionado', to='agenda_medico.agendamedica')),
            ],
        ),
    ]
