# Generated by Django 4.2.6 on 2023-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_profissional_options_alter_profissional_imagem'),
        ('agenda_medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendamedica',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medico.profissional'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='agenda_medica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_selecionado', to='agenda_medico.agendamedica'),
        ),
    ]
