# Generated by Django 5.0 on 2023-12-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medico', '0001_initial'),
        ('agendamento', '0001_initial'),
        ('paciente', '0002_paciente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agenda_medica',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agenda_medico.agendamedica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='agenda_medica',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='agenda_medico.agendamedica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_selecionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='horario_selecionado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente'),
        ),
    ]
