# Generated by Django 4.2.6 on 2023-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medico', '0002_horario_disponivel_alter_agendamedica_profissional_and_more'),
        ('paciente', '0001_initial'),
        ('medico', '0002_alter_profissional_options_alter_profissional_imagem'),
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='paciente',
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], default='P', max_length=20)),
                ('agenda_medica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.agendamedica')),
                ('horario_selecionado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medico.profissional')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
