# Generated by Django 4.2.6 on 2023-12-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medico', '0001_initial'),
        ('paciente', '0001_initial'),
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_selecionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], default='P', max_length=20)),
                ('horario_selecionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
