# Generated by Django 4.2.6 on 2023-12-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medico', '0002_horario_disponivel_alter_agendamedica_profissional_and_more'),
        ('agendamento', '0002_remove_agendamento_paciente_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='horario_selecionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario'),
        ),
    ]
