# Generated by Django 4.2.6 on 2023-12-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('agenda_medico', '0001_initial'),
        ('agendamento', '0002_agendamento_horario_selecionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda_medico.horario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente'),
        ),
    ]
