# Generated by Django 4.2.6 on 2023-12-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_medico', '0001_initial'),
        ('agendamento', '0004_alter_agendamento_horario_selecionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agenda_medica',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agenda_medico.agendamedica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='agenda_medica',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='agenda_medico.agendamedica'),
            preserve_default=False,
        ),
    ]
